version: 2
updates:
- package-ecosystem: nuget
  directory: "/src"
  schedule:
    interval: daily
    time: "00:00"
    timezone: Etc/UCT
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: MarkdownSnippets
    versions:
    - ">= 10.0.1.a, < 10.0.2"
  - dependency-name: MarkdownSnippets
    versions:
    - "> 16.3.1, < 16.4"
  - dependency-name: MarkdownSnippets
    versions:
    - "> 17.0.0, < 17.1"
  - dependency-name: MarkdownSnippets
    versions:
    - "> 20.0.0, < 20.1"
  - dependency-name: MarkdownSnippets
    versions:
    - ">= 21.4.a, < 21.5"
  - dependency-name: MarkdownSnippets
    versions:
    - "> 21.6.0, < 21.7"
  - dependency-name: MarkdownSnippets
    versions:
    - "> 9.1.0, < 9.2"
  - dependency-name: Microsoft.Azure.ServiceBus
    versions:
    - ">= 4.0.a, < 4.1"
  - dependency-name: Microsoft.Azure.ServiceBus
    versions:
    - "< 4, >= 3.a"
  - dependency-name: Microsoft.Azure.ServiceBus
    versions:
    - ">= 4.a, < 5"
  - dependency-name: Microsoft.Azure.ServiceBus
    versions:
    - ">= 5.a, < 6"
  - dependency-name: Microsoft.Azure.Storage.Blob
    versions:
    - "> 11.1.0, < 12"
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - "> 16.1.0, < 16.2"
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - "> 16.8.0, < 16.9"
  - dependency-name: PublicApiGenerator
    versions:
    - "> 10.0.0, < 10.1"
  - dependency-name: WindowsAzure.Storage
    versions:
    - "< 10, >= 9.a"
  - dependency-name: WindowsAzure.Storage
    versions:
    - "< 9, > 8.5.0"
  - dependency-name: MarkdownSnippets
    versions:
    - 22.0.3
    - 23.0.1
    - 23.0.2
    - 23.1.0
    - 23.1.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
